export const KEEPNOTE_LIST_REQUEST = "KEEPNOTE_LIST_REQUEST";
export const KEEPNOTE_LIST_SUCCESS = "KEEPNOTE_LIST_SUCCESS";
export const KEEPNOTE_LIST_FAILURE = "KEEPNOTE_LIST_FAILURE";

export const CREATE_KEEPNOTE_REQUEST = "CREATE_KEEPNOTE_REQUEST";
export const CREATE_KEEPNOTE_SUCCESS = "CREATE_KEEPNOTE_SUCCESS";
export const CREATE_KEEPNOTE_FAILURE = "CREATE_KEEPNOTE_FAILURE";

export const UPDATE_KEEPNOTE_REQUEST = "UPDATE_KEEPNOTE_REQUEST";
export const UPDATE_KEEPNOTE_SUCCESS = "UPDATE_KEEPNOTE_SUCCESS";
export const UPDATE_KEEPNOTE_FAILURE = "UPDATE_KEEPNOTE_FAILURE";

export const DELETE_KEEPNOTE_REQUEST = "DELETE_KEEPNOTE_REQUEST";
export const DELETE_KEEPNOTE_SUCCESS = "DELETE_KEEPNOTE_SUCCESS";
export const DELETE_KEEPNOTE_FAILURE = "DELETE_KEEPNOTE_FAILURE";
